# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image.
FROM node:18 AS build

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json files
COPY package.json package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Build the application
RUN npm run build

# Use a lightweight image to run the application
FROM node:18-slim

# Set the working directory
WORKDIR /app

# Copy the build output and node_modules from the build stage
COPY --from=build /app/build /app/build
COPY --from=build /app/node_modules /app/node_modules
COPY --from=build /app/package.json /app/package.json

# Define environment variables
ENV ROAM_API_TOKEN=your-api-token
ENV ROAM_GRAPH_NAME=your-graph-name
ENV MEMORIES_TAG='#[[LLM/Memories]]'

# Command to run the MCP server
ENTRYPOINT ["node", "build/index.js"]